use chrono::{DateTime, Local};
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Clone, Serialize, Deserialize)] #[serde(rename_all = "camelCase")] pub struct EventProposal { pub event_type: String, pub summary: String, pub importance: f32, pub location: String, pub xp_delta: i32, pub relationship_target: Option<String>, pub relationship_delta: i32 }
#[derive(Clone, Serialize, Deserialize)] pub struct WorldSnapshot { pub world_time: String, pub last_update: String, pub important_today: i32 }
pub struct Engine { db: Connection, root: PathBuf }
impl Engine {
 pub fn open() -> rusqlite::Result<Self> { let root=dirs_path(); std::fs::create_dir_all(&root).ok(); let db=Connection::open(root.join("world.sqlite3"))?; let e=Self{db,root}; e.migrate()?; Ok(e) }
 fn migrate(&self)->rusqlite::Result<()> { self.db.execute_batch("CREATE TABLE IF NOT EXISTS world_state (key TEXT PRIMARY KEY,value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events (id TEXT PRIMARY KEY,timestamp TEXT NOT NULL,type TEXT NOT NULL,summary TEXT NOT NULL,importance REAL NOT NULL,location TEXT NOT NULL,causes TEXT NOT NULL); CREATE TABLE IF NOT EXISTS personality_evidence (id INTEGER PRIMARY KEY,trait TEXT NOT NULL,delta INTEGER NOT NULL,event_id TEXT NOT NULL,reason TEXT NOT NULL); CREATE TABLE IF NOT EXISTS relationships (npc_id TEXT PRIMARY KEY,score INTEGER NOT NULL,stage TEXT NOT NULL); CREATE TABLE IF NOT EXISTS shared_experiences (id INTEGER PRIMARY KEY,event_ids TEXT NOT NULL,summary TEXT NOT NULL); CREATE TABLE IF NOT EXISTS inventory (id TEXT PRIMARY KEY,name TEXT NOT NULL,quantity INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS skills (id TEXT PRIMARY KEY,name TEXT NOT NULL,level INTEGER NOT NULL,experience INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS goals (id TEXT PRIMARY KEY,description TEXT NOT NULL,progress INTEGER NOT NULL,target INTEGER NOT NULL,completed INTEGER NOT NULL);")?; Ok(()) }
 pub fn snapshot(&self)->rusqlite::Result<WorldSnapshot>{let now=Local::now();let count:i32=self.db.query_row("SELECT count(*) FROM events WHERE type='important_event' AND timestamp LIKE ?1",[format!("{}%",now.format("%Y-%m-%d"))],|r|r.get(0)).unwrap_or(0);Ok(WorldSnapshot{world_time:now.format("%H:%M").to_string(),last_update:now.to_rfc3339(),important_today:count})}
 pub fn apply(&mut self,p:EventProposal)->rusqlite::Result<WorldSnapshot>{if p.event_type=="no_event" { return self.snapshot(); } if p.summary.trim().is_empty() || p.summary.chars().count()>160{return Err(rusqlite::Error::InvalidParameterName("summary must be 1-160 characters".into()))}let allowed=["normal_event","social_event","activity_event","important_event","milestone_event"];if !allowed.contains(&p.event_type.as_str()){return Err(rusqlite::Error::InvalidParameterName("invalid event type".into()))}let xp=p.xp_delta.clamp(0,50);let rel=p.relationship_delta.clamp(-5,5);let id=format!("event-{}",Local::now().timestamp_millis());let timestamp:DateTime<Local>=Local::now();let tx=self.db.transaction()?;tx.execute("INSERT INTO events VALUES (?1,?2,?3,?4,?5,?6,?7)",params![id,timestamp.to_rfc3339(),p.event_type,p.summary,p.importance.clamp(0.0,1.0),p.location,"[]"])?;tx.execute("INSERT OR REPLACE INTO world_state(key,value) VALUES ('last_xp_delta',?1)",[xp.to_string()])?;tx.execute("INSERT OR REPLACE INTO world_state(key,value) VALUES ('last_relationship_delta',?1)",[rel.to_string()])?;tx.execute("INSERT OR REPLACE INTO world_state(key,value) VALUES ('last_update',?1)",[timestamp.to_rfc3339()])?;tx.execute("INSERT OR REPLACE INTO world_state(key,value) VALUES ('next_normal_check',?1)",[timestamp.timestamp()+1800])?;tx.commit()?;self.snapshot()}
}
fn dirs_path()->PathBuf { std::env::var_os("AI_WORLD_DATA").map(PathBuf::from).unwrap_or_else(||std::env::current_dir().unwrap().join("data")) }
