import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { BookOpen, Brain, ChevronRight, CircleHelp, CloudRain, Cog, Download, Heart, History, Home, Moon, MoreHorizontal, Package, Pause, Play, Plus, RefreshCw, Settings, Sparkles, Users, Zap } from 'lucide-react';
import { applyEvent, createOfflineEvent, initialState } from './simulation';
import type { EventRecord, PetState } from './types';

const nav = [{ icon: Home, label: '世界' }, { icon: History, label: '编年史' }, { icon: Users, label: '关系' }, { icon: Package, label: '物品' }, { icon: Brain, label: '性格' }];
type SettingsState = { baseUrl: string; model: string; apiKey: string; sidebarEvents: number; fps: number; realTime: boolean };

function Progress({ value, color = '#d66b62' }: { value: number; color?: string }) { return <div className="progress"><span style={{ width: `${Math.min(100, value)}%`, background: color }} /></div>; }
function EventItem({ event }: { event: EventRecord }) { const important = event.type === 'important_event'; return <article className={`event ${important ? 'important' : ''}`}><div className="event-time">{important && <Sparkles size={13} />} {event.timestamp}<span>{event.location}</span></div><p>{event.summary}</p>{important && <div className="event-tag">IMPORTANT EVENT <ChevronRight size={12} /></div>}</article>; }

function PetStage({ state, onClick }: { state: PetState; onClick: () => void }) { return <section className="stage"><div className="stage-top"><span className="live-dot" /> WORLD IS ALIVE <span className="stage-date">SEP 02, 2026</span></div><div className="weather"><CloudRain size={17} /> {state.weather}</div><div className="scene"><div className="sun" /><div className="window"><i /><i /><i /></div><div className="shelf"><b /><b /><b /><b /><b /></div><div className="desk"><span className="lamp" /><span className="book-stack" /></div><div className="plant"><span /><em /></div><button className={`pet ${state.animation}`} onClick={onClick} aria-label="查看 Aoi 状态"><div className="pet-shadow" /><div className="pet-hair" /><div className="pet-face"><i /><i /><b /></div><div className="pet-body" /><div className="pet-dress" /></button><div className="speech">{state.status}<small>·</small></div><div className="floor" /></div><div className="stage-footer"><div><span className="eyebrow">CURRENT LOCATION</span><strong><BookOpen size={17} /> {state.location}</strong></div><div className="stage-actions"><button title="暂停模拟"><Pause size={15} /></button><button title="更多操作"><MoreHorizontal size={17} /></button></div></div></section>; }

function Overview({ state }: { state: PetState }) { return <><section className="identity"><div className="identity-avatar">A<span className="online" /></div><div><h1>{state.name}</h1><p>quiet · curious · kind</p></div><span className="level">LV. {state.level}</span><button className="icon-button"><Settings size={17} /></button></section><section className="xp-block"><div className="row-label"><span>EXPERIENCE</span><b>{state.xp} <small>/ {state.nextXp} XP</small></b></div><Progress value={state.xp / state.nextXp * 100} /><div className="row-label muted"><span>UNTIL LEVEL {state.level + 1}</span><span>{Math.max(0, state.nextXp - state.xp)} XP TO GO</span></div></section><div className="stat-grid"><div><Moon size={17} /><span>MOOD</span><strong>{state.mood}<small>/ 100</small></strong><Progress value={state.mood} color="#e4b75c" /></div><div><Zap size={17} /><span>ENERGY</span><strong>{state.energy}<small>/ 100</small></strong><Progress value={state.energy} color="#5c9a9b" /></div></div><section className="panel-section"><div className="section-title"><span>PERSONALITY</span><button>VIEW ALL <ChevronRight size={13} /></button></div>{state.traits.map(t => <div className="trait" key={t.name}><span>{t.name}</span><Progress value={t.score} color={t.color} /><b>{t.score}</b></div>)}</section><section className="panel-section"><div className="section-title"><span>GOALS IN PROGRESS</span><button>VIEW ALL <ChevronRight size={13} /></button></div>{state.goals.map(g => <div className="goal" key={g.name}><div><strong>{g.name}</strong><span>{g.progress}% complete</span></div><Progress value={g.progress} color="#7582b6" /></div>)}</section></>; }

function Sidebar({ state, onAdd }: { state: PetState; onAdd: () => void }) { return <aside className="sidebar"><div className="sidebar-head"><div><span className="eyebrow">YOUR COMPANION</span><h2>Character overview</h2></div><button className="icon-button"><MoreHorizontal size={18} /></button></div><Overview state={state} /><section className="panel-section inventory"><div className="section-title"><span>RECENTLY FOUND</span><button>INVENTORY <ChevronRight size={13} /></button></div>{state.inventory.map(item => <div className="item" key={item.name}><div className="item-icon"><BookOpen size={16} /></div><div><strong>{item.name}</strong><span>{item.detail}</span></div></div>)}</section><section className="panel-section people"><div className="section-title"><span>PEOPLE IN HER WORLD</span><button onClick={onAdd}><Plus size={14} /> ADD</button></div>{state.npcs.map(npc => <div className="person" key={npc.id}><div className="person-avatar">{npc.avatar}</div><div><strong>{npc.name}</strong><span>{npc.role}</span></div><div className="heart"><Heart size={13} fill="currentColor" /> {npc.relationship}</div></div>)}</section></aside>; }

function SettingsPanel({ settings, onChange, onClose, onTest }: { settings: SettingsState; onChange: (next: SettingsState) => void; onClose: () => void; onTest: () => void }) { return <div className="modal-backdrop" onMouseDown={onClose}><section className="settings-panel" onMouseDown={event => event.stopPropagation()}><div className="settings-header"><div><span className="eyebrow">WORLD CONFIGURATION</span><h2>Settings</h2></div><button className="icon-button" onClick={onClose} aria-label="关闭"><ChevronRight size={18} style={{ transform: 'rotate(90deg)' }} /></button></div><div className="settings-group"><span className="settings-label">AI PROVIDER</span><label>Base URL<input value={settings.baseUrl} onChange={event => onChange({ ...settings, baseUrl: event.target.value })} placeholder="https://example.com/v1" /></label><label>Model<input value={settings.model} onChange={event => onChange({ ...settings, model: event.target.value })} placeholder="your-model" /></label><label>API Key<input type="password" value={settings.apiKey} onChange={event => onChange({ ...settings, apiKey: event.target.value })} placeholder="Stored in OS keychain for desktop builds" /></label><button className="outline-action" onClick={onTest}><RefreshCw size={14} /> TEST CONNECTION</button></div><div className="settings-grid"><label>Sidebar events<select value={settings.sidebarEvents} onChange={event => onChange({ ...settings, sidebarEvents: Number(event.target.value) })}><option value="5">5</option><option value="10">10</option><option value="20">20</option><option value="30">30</option></select></label><label>Animation FPS<input type="number" min="1" max="30" value={settings.fps} onChange={event => onChange({ ...settings, fps: Number(event.target.value) })} /></label></div><div className="toggle-row"><span><strong>Real-time mode</strong><small>1 real minute = 1 world minute</small></span><button className={`toggle ${settings.realTime ? 'on' : ''}`} onClick={() => onChange({ ...settings, realTime: !settings.realTime })}><i /></button></div><div className="settings-footer"><button className="text-action" onClick={() => { if (window.confirm('This will delete all character progress, memories, relationships and event history. Continue?')) { localStorage.removeItem('aoi-world-state'); location.reload(); } }}>RESET WORLD</button><button className="primary-action" onClick={onClose}>SAVE SETTINGS</button></div></section></div>; }

export default function App() {
  const [state, setState] = useState<PetState>(() => { const saved = localStorage.getItem('aoi-world-state'); return saved ? JSON.parse(saved) : initialState; });
  const [tab, setTab] = useState('世界'); const [running, setRunning] = useState(true); const [toast, setToast] = useState(''); const [settingsOpen, setSettingsOpen] = useState(false);
  const [settings, setSettings] = useState<SettingsState>(() => { const saved = localStorage.getItem('aoi-world-settings'); return saved ? { ...JSON.parse(saved), apiKey: '' } : { baseUrl: '', model: '', apiKey: '', sidebarEvents: 10, fps: 8, realTime: true }; });
  useEffect(() => localStorage.setItem('aoi-world-state', JSON.stringify(state)), [state]);
  useEffect(() => { const { apiKey: _apiKey, ...safeSettings } = settings; localStorage.setItem('aoi-world-settings', JSON.stringify(safeSettings)); }, [settings]);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setState(current => applyEvent(current, createOfflineEvent(current))), 60000); return () => window.clearInterval(timer); }, [running]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400); };
  const addEvent = async () => { const event = createOfflineEvent(state); setState(current => applyEvent(current, event)); try { await invoke('apply_proposal', { proposal: { eventType: event.type, summary: event.summary, importance: event.importance, location: event.location, xpDelta: 5, relationshipTarget: null, relationshipDelta: 0 } }); } catch { /* Browser preview and offline mode use the local event. */ } notify('已记录一段新的日常'); };
  const testProvider = async () => { try { await invoke('test_provider', { baseUrl: settings.baseUrl, model: settings.model }); notify('Provider 配置已通过基础检查'); } catch { notify(settings.baseUrl && settings.model ? '浏览器预览：配置已保存' : '请先填写 Base URL 和 Model'); } };
  return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark">✦</div><div><strong>AOI'S WORLD</strong><span>PERSISTENT CHARACTER SIMULATION</span></div></div><div className="world-clock"><span className="live-dot" /><span>REAL WORLD TIME</span><b>{new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</b></div><div className="top-actions"><button className="icon-button" title="帮助"><CircleHelp size={18} /></button><button className="icon-button" title="设置" onClick={() => setSettingsOpen(true)}><Cog size={18} /></button><button className="avatar-button">Z</button></div></header><div className="layout"><nav className="nav">{nav.map(item => { const Icon = item.icon; return <button key={item.label} className={tab === item.label ? 'active' : ''} onClick={() => setTab(item.label)}><Icon size={18} /><span>{item.label}</span></button>; })}<div className="nav-bottom"><button onClick={() => notify('世界数据已准备导出')}><Download size={18} /><span>导出世界</span></button><button onClick={() => setSettingsOpen(true)}><Settings size={18} /><span>设置</span></button></div></nav><main className="main"><div className="main-heading"><div><span className="eyebrow">WEDNESDAY · SEPTEMBER 02</span><h2>{tab === '世界' ? '她的世界' : tab}</h2></div><div className="engine-status"><span className="pulse" /> {running ? 'ENGINE RUNNING' : 'ENGINE PAUSED'} <button onClick={() => setRunning(!running)}>{running ? <Pause size={14} /> : <Play size={14} />}</button></div></div><div className="content-grid"><PetStage state={state} onClick={() => notify('Aoi 正在安静地读书')} /><section className="chronicle"><div className="section-title"><div><span className="eyebrow">RECENT ACTIVITY</span><h3>Chronicle</h3></div><button onClick={addEvent}><RefreshCw size={14} /> SIMULATE</button></div><div className="event-list">{state.events.slice(0, settings.sidebarEvents).map(event => <EventItem event={event} key={event.id} />)}</div><button className="load-more">LOAD EARLIER MEMORIES <ChevronRight size={14} /></button></section></div></main><Sidebar state={state} onAdd={() => notify('人物编辑器将在下一版开放')} /></div>{toast && <div className="toast"><Sparkles size={15} />{toast}</div>}{settingsOpen && <SettingsPanel settings={settings} onChange={setSettings} onClose={() => setSettingsOpen(false)} onTest={testProvider} />}</div>;
}
